export const FRUITS = [
    "Abiu",
    "Acerola",
    "Akebi",
    "Ackee",
    "African Cherry Orange",
    "American Mayapple",
    "Apple",
    "Apricot",
    "Aratiles",
    "Araza",
    "Avocado",
    "Banana",
    "Bilberry",
    "Blackberry",
    "Blackcurrant",
    "Black sapote",
    "Blueberry",
    "Boysenberry",
    "Breadfruit",
    "Cactus pear",
    "Canistel",
    "Catmon",
    "Cempedak",
    "Cherimoya",
    "Cherry",
    "Chico fruit",
    "Cloudberry",
    "Coco de mer",
    "Coconut",
    "Crab apple",
    "Cranberry",
    "Currant",
    "Damson",
    "Date",
    "Dragonfruit",
    "Durian",
    "Elderberry",
    "Feijoa",
    "Fig",
    "Finger Lime",
    "Gac",
    "Goji berry",
    "Gooseberry",
    "Grape",
    "Raisin",
    "Grapefruit",
    "Grewia asiatica",
    "Guava",
    "Hala fruit",
    "Haws",
    "Honeyberry",
    "Huckleberry",
    "Jabuticaba",
    "Jackfruit",
    "Jambul",
    "Japanese plum",
    "Jostaberry",
    "Jujube",
    "Juniper berry",
    "Kaffir lime",
    "Kiwano",
    "Kiwifruit",
    "Kumquat",
    "Lanzones",
    "Lemon",
    "Lime",
    "Loganberry",
    "Longan",
    "Loquat",
    "Lulo",
    "Lychee",
    "Magellan Barberry",
    "Macopa",
    "Mamey apple",
    "Mamey Sapote",
    "Mango",
    "Mangosteen",
    "Marionberry",
    "Medlar",
    "Melon",
    "Cantaloupe",
    "Galia melon",
    "Honeydew",
    "Mouse melon",
    "Muskmelon",
    "Watermelon",
    "Miracle fruit",
    "Momordica fruit",
    "Monstera deliciosa",
    "Mulberry",
    "Nance",
    "Nectarine",
    "Orange",
    "Blood orange",
    "Clementine",
    "Mandarine",
    "Tangerine",
    "Papaya",
    "Passionfruit",
    "Pawpaw",
    "Peach",
    "Pear",
    "Persimmon",
    "Plantain",
    "Plum",
    "Prune",
    "Pineapple",
    "Pineberry",
    "Plumcot",
    "Pomegranate",
    "Pomelo",
    "Quince",
    "Raspberry",
    "Salmonberry",
    "Rambutan",
    "Redcurrant",
    "Rose apple",
    "Salal berry",
    "Salak",
    "Santol",
    "Sapodilla",
    "Sapote",
    "Sarguelas",
    "Satsuma",
    "Sloe",
    "Soursop",
    "Star apple",
    "Star fruit",
    "Strawberry",
    "Sugar apple",
    "Suriname cherry",
    "Tamarillo",
    "Tamarind",
    "Tangelo",
    "Tayberry",
    "Thimbleberry",
    "Ugli fruit",
    "White currant",
    "White sapote",
    "Ximenia"
  ];

